vscode:
  extensions:
    - philsinatra.popping-and-locking-vscode-black@1.1.7:9ATXO4H+slSkAIB8QPoRUg==
    - steoates.autoimport@1.5.3:ssEPucpXsRjqSbJX1bW0YA==
    - oderwat.indent-rainbow@7.4.0:nth8lnJRnQu9NcWvNc9KPA==
    - dsznajder.es7-react-js-snippets@2.6.0:NOQZR885dDDgg5u9iE3Cmg==